# Generated by Django 3.0.7 on 2022-04-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('costo', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('fecha_de_reistro', models.DateField()),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('nombre_receta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cantidad_gramos', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.Ingredientes')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.Receta')),
            ],
        ),
    ]
