# Generated by Django 3.0.7 on 2022-04-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientes',
            old_name='fecha_de_reistro',
            new_name='fecha_de_registro',
        ),
    ]
