# Generated by Django 2.2.3 on 2022-04-24 15:41

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_auto_20220424_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientesreceta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientesreceta',
            name='valor',
            field=models.IntegerField(default=sqlalchemy.sql.expression.null),
        ),
    ]
